[project]
name = "anvil-code"
version = "0.1.0"
description = "A simple toy code agent powered by OpenRouter"
readme = "README.md"
authors = [
    { name = "Atank", email = "atank@atank.org" }
]
requires-python = ">=3.13"
dependencies = [
    "openai==2.44.0",
    "python-dotenv==1.1.0",
]

[project.scripts]
anvil-code = "anvil_code.main:main"


[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
